### ISSUE TITLE
Incorrect results with asynchronous partitioning on CUDA devices and STARPU 1.4. 

### ISSUE THREAD

**Issue by grisuthedragon** [starpu-runtime/starpu#37]
It seems that during the updates introduces between 1.3 and 1.4, the asynchronous partitioning is broken. In basic, we have a code
```
starpu_data_partion_plan(....) ; 

execute tasks on the partioned dataset

starpu_data_partition_clean(...); 
```
The submit / unsubmit we leave to the STARPU runtime. The kernels required for the computing the task are available as CPU and CUDA implementation. Now we observed the following cases. 

## StarPU 1.3.11 / CUDA 11.8 / GCC 12

- CPU Only. Everything Correct 
- 64 CPU Cores + 1 CUDA Device:  Everything Correct 
- 64 CPU Cores + 4 CUDA Devices:  Everything Correct 

## StarPU 1.3.11 / CUDA 12.2/ GCC 12

- CPU Only. Everything Correct 
- 64 CPU Cores + 1 CUDA Device:  Everything Correct 
- 64 CPU Cores + 4 CUDA Devices:  Everything Correct 

## StarPU 1.4.4 / CUDA 12.2/ GCC 12

- CPU Only. Everything Correct 
- 64 CPU Cores + 1 CUDA Device:  Wrong results. 
- 64 CPU Cores + 4 CUDA Devices:  Wrong results. 

The tasks are only gemm operations from CUBLAS or MKL. 
Due to ongoing research, I could not share the code and does not have time to build an MWE til now.  But in general it seems to have something in common with https://gitlab.inria.fr/starpu/starpu/-/issues/43.

**Comment by grisuthedragon** [comment]
So I could write a MWE example performing a GEMM on CPU oder GPU. 

https://gist.github.com/grisuthedragon/0fa99935086a5945171ef63f185bbcee

With 
```
STAPU_NCUDA=0 STARPU_SCHED=dmdas ./gemm_gpu
```
it works.

With 
```
STAPU_NCUDA=1 STARPU_SCHED=dmdas ./gemm_gpu
```
it gives sometimes random errors. 

And with 
```
STAPU_NCUDA=4 STARPU_SCHED=dmdas ./gemm_gpu
```
permanently fails.

If it fails, it seems that the execution got slow before.

The same holds true for `dmda`, `lws`, ... schedulers

GCC: 12
STARPU: 1.4.4
CUDA: 12.2.128 / 4x A100
CPU: AMD Epyc 2x 32 Cores

**Comment by sthibaul** [comment]
Hello,

I tried your MWE, but I'm getting 

`The codelet <gemm_kernel> defines the access mode 3 for the buffer 2 which is different from the mode 2 given to starpu_task_insert`

and indeed the codelet says `STARPU_RW` for the last argument, while the insert call is `STARPU_W` (and thus not a wonder that computation is getting wrong since it doesn't declare to starpu that it wants to read the previous value)

**Comment by grisuthedragon** [comment]
Sorry, that was a copy and paste error. But changing the call in the `beta == 1` case to `STARPU_RW` it results in the same incorrect results. I updated the gist as well. 


Btw. I did not get your error message.

**Comment by sthibaul** [comment]
>  I did not get your error message.

If you configure with `--enable-fast`, you're jumping without a parachute

> changing the call in the `beta == 1` case to `STARPU_RW` it results in the same incorrect results

I do get correct results on a 3-gpu machine, with various schedulers.

**Comment by grisuthedragon** [comment]
I installed StarPU via Spack and disabled `enable-fast` by now, but it does not change the behavior when using cuda. 

Here is my environment file for spack: `spack.yaml`:
```
spack:
  # add package specs to the `specs` list
  specs:
  - gcc@12.3.0+binutils+graphite
  - starpu@1.4.4~mpi+cuda~fast
  - hdf5+hl~mpi
  - cmake
  - intel-oneapi-mkl threads=openmp
  - cuda@12.2
  - gdb
  - hwloc
  view: true
  concretizer:
    unify: true
  packages:
    all:
      compiler:
        - gcc@12.3.0
```

The code runs on 
-  CentOS 7.9 
-  2x AMD Epyc  AMD EPYC 7452
-  4x Nvidia A100
- CUDA 12.2 , CUDA Driver:  535.86.10

**Comment by grisuthedragon** [comment]
I did some additional test with varying BLAS implementations and got the following results

Intel OneMKL + CUDA 12.2 + GCC12 + StarPU 1.4.4:
 - oneMKL 2021.4.0 - **failed** 
 - oneMKL 2022.2.1 - **failed**
 - oneMKL 2023.0.0 - **failed**
 - oneMKL 2024.0.0 - **failed**
 - oneMKL 2024.1.0 - **failed**

OpenBLAS 0.3.26 + CUDA 12.2 + GCC12  + StarPU 1.4.4:
 - Very slow, **failed**
 
 @sthibaul Can you give some more details about your environment?

**Comment by sthibaul** [comment]
I used this source: @
[gemm_gpu.c.txt](https://github.com/starpu-runtime/starpu/files/15080316/gemm_gpu.c.txt)


with this spec:

```
spack:
  # add package specs to the `specs` list
  specs:
  - gcc@12.3.0+binutils+graphite
  - starpu@1.4.4~mpi+cuda~fast
  - hdf5+hl~mpi
  - cmake
  - intel-oneapi-mkl threads=openmp
  - cuda@12.3
  - gdb
  - hwloc
  view: true
  concretizer:
    unify: true
  packages:
    all:
      compiler:
      - gcc@12.2.0
    cuda:
      buildable: false
      externals:
      - spec: cuda@12.3
        prefix: /usr/local/cuda-12.3/
  compilers:
  - compiler:
      spec: gcc@=12.2.0
      paths:
        cc: /cm/shared/modules/intel/skylake/compiler/gcc/12.2.0/bin/gcc
        cxx: /cm/shared/modules/intel/skylake/compiler/gcc/12.2.0/bin/g++
        f77: /cm/shared/modules/intel/skylake/compiler/gcc/12.2.0/bin/gfortran
        fc: /cm/shared/modules/intel/skylake/compiler/gcc/12.2.0/bin/gfortran
      flags: {}
      operating_system: centos7
      target: x86_64
      modules: []
      environment: {}
      extra_rpaths: []
```

compiled with 

```
gcc --std=gnu99 gemm_gpu.c -o gemm_gpu $( pkg-config --cflags starpu-1.4) $(pkg-config --libs starpu-1.4)  -lcublas -lmkl_intel_lp64 -lmkl_sequential -lmkl_core
```

ran with

```
STARPU_WORKER_STATS=1 STARPU_SCHED=dmdas ./gemm_gpu
```

On Centos 7.6.1810, with two gpus, without any error.

I tried to add `A[0]++` in the cpu codelet to make sure that errors get catched, and they do.

Note: the mkl/openblas library probably doesn't matter since you said it was when adding gpus that you had issues. You can even try with `STARPU_NCPU=0` to rule out the cpu question.
